/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/O5rRUVnDNbQ
 */
import {
  CardTitle,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
  TableFooter,
} from "@/components/ui/table";

import { Button } from "@/components/ui/Button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { formatCurrency } from "@/lib/formatCurrency";
import { Portfolio } from "@prisma/client";

export function PortfolioAssets({ id }: Pick<Portfolio, "id">) {
  const assets = [
    {
      name: "Cash",
      type: "Cash",
      quantity: 100000,
      worth: 100000,
      percentage: 40,
    },
    {
      name: "EDO",
      type: "Treasure Bonds",
      quantity: 1000,
      worth: 100000,
      percentage: 40,
    },
    {
      name: "ETFSP500",
      type: "ETF",
      quantity: 1000,
      worth: 100000,
      percentage: 40,
    },
    {
      name: "Gold",
      type: "Commodity",
      quantity: 100000,
      worth: 100000,
      percentage: 40,
    },
  ];
  const total = assets.reduce((acc, asset) => acc + asset.worth, 0);
  const types = ["Cash", "Treasure Bonds", "ETF", "Commodity"];
  return (
    <Card className="col-span-2 w-full max-w-2xl">
      <CardHeader>
        <CardTitle>Assets in Portfolio</CardTitle>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Asset Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Quantity</TableHead>
              <TableHead>Estimated Worth</TableHead>
              <TableHead>Percentage of Portfolio</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {assets.map((asset) => (
              <TableRow key={asset.name}>
                <TableCell className="font-medium">{asset.name}</TableCell>
                <TableCell>{asset.type}</TableCell>
                <TableCell>{asset.quantity}</TableCell>
                <TableCell>{formatCurrency(asset.worth, "PLN")}</TableCell>
                <TableCell>{asset.percentage}%</TableCell>
              </TableRow>
            ))}
          </TableBody>
          <TableFooter>
            <TableRow>
              <TableCell colSpan={3}>Total</TableCell>
              <TableCell>{formatCurrency(total, "PLN")}</TableCell>
              <TableCell>100%</TableCell>
            </TableRow>
          </TableFooter>
        </Table>
      </CardContent>
      <CardFooter>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline">Add Asset</Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            {types.map((type) => (
              <DropdownMenuItem key={type}>{type}</DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
      </CardFooter>
    </Card>
  );
}
