/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SVLNtDHTNN7
 */
import {
  CardDescription,
  CardHeader,
  CardContent,
  Card,
  CardTitle,
} from "@/components/ui/card";
import { formatCurrency } from "@/lib/formatCurrency";

type PortfolioDetailsProps = {
  type: string;
  goal: number | null;
  description: string | null;
};

export function PortfolioDetails({
  type,
  goal,
  description,
}: PortfolioDetailsProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{type}</CardTitle>
        <Goal goal={goal} />
      </CardHeader>
      <Description description={description} />
    </Card>
  );
}

const Goal = ({ goal }: Pick<PortfolioDetailsProps, "goal">) => {
  if (!goal) return null;
  return <CardDescription>Goal: {formatCurrency(goal, "PLN")}</CardDescription>;
};

const Description = ({
  description,
}: Pick<PortfolioDetailsProps, "description">) => {
  if (!description) return null;
  return (
    <CardContent>
      <p className="text-gray-700 dark:text-gray-300">{description}</p>
    </CardContent>
  );
};
