/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VPdxDRlwlS3
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "./ui/card";
import { Label } from "./ui/label";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "./ui/select";
import { Button } from "./ui/Button";
import {
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./ui/dialog";

export function Settings() {
  const languages = ["english", "polish"];
  const chosenLanguage = "english";

  const currencies = ["USD", "EUR", "PLN"];
  const chosenCurrency = "PLN";

  const themes = ["light", "dark"];
  const chosenTheme = "light";

  return (
    <DialogContent className="w-72">
      <form>
        <DialogHeader>
          <DialogTitle>Settings</DialogTitle>
          <DialogDescription>Customize your preferences.</DialogDescription>
        </DialogHeader>
        <div className="flex flex-col gap-4 py-8">
          <div>
            <Label htmlFor="language">Language</Label>
            <Select name="language" defaultValue={chosenLanguage}>
              <SelectTrigger>
                <SelectValue></SelectValue>
              </SelectTrigger>
              <SelectContent>
                {languages.map((language) => (
                  <SelectItem key={language} value={language}>
                    {language}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="currency">Currency</Label>
            <Select name="currency" defaultValue={chosenCurrency}>
              <SelectTrigger>
                <SelectValue></SelectValue>
              </SelectTrigger>
              <SelectContent>
                {currencies.map((currency) => (
                  <SelectItem key={currency} value={currency}>
                    {currency}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="theme">Theme</Label>
            <Select name="theme" defaultValue={chosenTheme}>
              <SelectTrigger>
                <SelectValue></SelectValue>
              </SelectTrigger>
              <SelectContent>
                {themes.map((theme) => (
                  <SelectItem key={theme} value={theme}>
                    {theme}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        <DialogFooter>
          <Button type="submit" className="ml-auto">
            Save
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  );
}
