/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/m8PO5Rcg0L0
 */
import Link from "next/link";
import { ReactNode, SVGProps } from "react";
import { twMerge } from "tailwind-merge";
import { ProfileInfo } from "./ProfileInfo";

export function Sidebar({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) {
  return (
    <div className="flex flex-col bg-gray-100/40 dark:bg-gray-800/40">
      <div className="flex h-full max-h-screen flex-col gap-2">
        <div className="flex h-16 items-center border-b px-6">
          <Link className="flex items-center gap-2 font-semibold" href="#">
            <CodeIcon className="h-6 w-6" />
            <span>KoderKash</span>
          </Link>
        </div>
        <div className="flex-1 overflow-auto py-2">
          <nav className="grid items-start px-4 text-sm font-medium">
            {children}
          </nav>
        </div>
      </div>
      <div className="flex items-center justify-center p-2">
        <ProfileInfo />
      </div>
    </div>
  );
}

type NavItemProps = {
  href: string;
  icon: ReactNode;
  children: ReactNode;
  active?: boolean;
};

export function NavItem({ href, children, icon, active }: NavItemProps) {
  return (
    <Link
      className={twMerge(
        "flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50",
        active && "bg-gray-200 dark:bg-gray-700 dark:text-gray-50",
      )}
      href={href}
    >
      {icon}
      {children}
    </Link>
  );
}

function CodeIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}
